name: non-profit

services:
  web:
    build: .
    environment:
      - "USER=${USER}"
      - "UID=1000"
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules